// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 7268zCZ6kAw6aCYdiP2nzq
// Component: SrqqiSOoby7M
import * as React from "react";
import {
  PlasmicImg as PlasmicImg__,
  Stack as Stack__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  hasVariant,
  initializeCodeComponentStates,
  useCurrentUser,
  useDollarState
} from "@plasmicapp/react-web";
import { useDataEnv } from "@plasmicapp/react-web/lib/host";
import NavigationBar from "../../NavigationBar"; // plasmic-import: RFbCdE22SC2b/component
import { Reveal } from "@plasmicpkgs/react-awesome-reveal";
import ProjectCard from "../../ProjectCard"; // plasmic-import: cVqtfftHOAsH/component
import ContactSection from "../../ContactSection"; // plasmic-import: TU3Z218kSa9l/component
import Footer from "../../Footer"; // plasmic-import: 9OA69trFNc0m/component
import { AntdDatePicker } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import { datePickerHelpers as AntdDatePicker_Helpers } from "@plasmicpkgs/antd5/skinny/registerDatePicker";
import { useScreenVariants as useScreenVariantso1EIcjvXtqJ1 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: O1eICJVXtqJ1/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 7268zCZ6kAw6aCYdiP2nzq/projectcss
import sty from "./PlasmicHomepage.module.css"; // plasmic-import: SrqqiSOoby7M/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: CH7nz1upyjeu/icon
import StarIcon from "./icons/PlasmicIcon__Star"; // plasmic-import: Ahhgp1FRPHJh/icon
import uxDesignpngBLz1FLdJ3JVx from "./images/uxDesignpng.png"; // plasmic-import: BLz1fLdJ3jVx/picture
import brushpngR3QrLaI5Ix3S from "./images/brushpng.png"; // plasmic-import: r3qrLaI5ix3S/picture
import programmingpngVFumlm5Giy4X from "./images/programmingpng.png"; // plasmic-import: VFumlm5giy4x/picture
import abstractBackgroundJpg5P9VEsB5X25M from "./images/abstractBackgroundJpg.jpg"; // plasmic-import: 5P9VEsB5X25M/picture
import abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpgKbyRfUiqZq4S from "./images/abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpg.jpg"; // plasmic-import: kbyRFUiqZQ4s/picture
import blueAndOrangeAbstractBackgroundFreeVectorjpg9ViVfovKbrrw from "./images/blueAndOrangeAbstractBackgroundFreeVectorjpg.jpg"; // plasmic-import: 9VIVfovKbrrw/picture
import studentGa473640711280JpgRKsLA5I6R from "./images/studentGa473640711280Jpg.jpg"; // plasmic-import: -R-KS-lA5I6r/picture
import lukePetersB6JiNerWMz0Unsplashjpg2ZrK6L4HpVe1 from "./images/lukePetersB6JiNerWMz0Unsplashjpg.jpg"; // plasmic-import: 2ZrK6l4hpVe1/picture
import benKoldeBs2Ba7T69MMUnsplashjpgUWij0Ll9570 from "./images/benKoldeBs2Ba7T69MMUnsplashjpg.jpg"; // plasmic-import: u_wij0Ll9570/picture
import danielKorpaiAUmq852V7IUnsplashjpgLRgUox8TcW9 from "./images/danielKorpaiAUmq852V7IUnsplashjpg.jpg"; // plasmic-import: lRgUOX8TC_w9/picture
import alexSuprunZHvM3XioHoEUnsplashjpgLc7Tf8Rih8G from "./images/alexSuprunZHvM3XioHoEUnsplashjpg.jpg"; // plasmic-import: -lc7TF8RIH8G/picture
import christopherCampbellRDeoVtE7VOsUnsplashjpgBUqxgVggHjJ2 from "./images/christopherCampbellRDeoVtE7VOsUnsplashjpg.jpg"; // plasmic-import: BUqxgVGGHjJ2/picture
import courtneyCookTsZo17R3M0SUnsplashjpg7KDmPjoff0Od from "./images/courtneyCookTsZo17R3M0SUnsplashjpg.jpg"; // plasmic-import: 7KDmPjoff0OD/picture
import alexanderHippIEebWgY6LAUnsplashjpg4EMtYZpQeJWx from "./images/alexanderHippIEebWgY6LAUnsplashjpg.jpg"; // plasmic-import: 4EMtYZpQeJWx/picture

createPlasmicElementProxy;

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array();

const $$ = {};

function PlasmicHomepage__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;
  const currentUser = useCurrentUser?.() || {};
  const stateSpecs = React.useMemo(
    () => [
      {
        path: "dateTimePicker.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,
        onMutate: generateOnMutateForSpec("value", AntdDatePicker_Helpers)
      }
    ],

    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantso1EIcjvXtqJ1()
  });
  return (
    <React.Fragment>
      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <NavigationBar
            data-plasmic-name={"navigationBar"}
            data-plasmic-override={overrides.navigationBar}
            className={classNames("__wab_instance", sty.navigationBar)}
          />

          <Stack__
            as={"section"}
            data-plasmic-name={"intro"}
            data-plasmic-override={overrides.intro}
            hasGap={true}
            className={classNames(projectcss.all, sty.intro)}
          >
            <div className={classNames(projectcss.all, sty.freeBox___9CYpG)}>
              <div
                data-plasmic-name={"mainTextContainer"}
                data-plasmic-override={overrides.mainTextContainer}
                className={classNames(projectcss.all, sty.mainTextContainer)}
              >
                <h1
                  data-plasmic-name={"h1"}
                  data-plasmic-override={overrides.h1}
                  className={classNames(
                    projectcss.all,
                    projectcss.h1,
                    projectcss.__wab_text,
                    sty.h1
                  )}
                >
                  {"Hey there, Srijan here \ud83d\udc4b"}
                </h1>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__hwFbi
                  )}
                >
                  {"Web designer and product designer for hire."}
                </div>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__ugYnA
                  )}
                >
                  {"Enter some text"}
                </div>
              </div>
              <a
                data-plasmic-name={"link"}
                data-plasmic-override={overrides.link}
                className={classNames(projectcss.all, projectcss.a, sty.link)}
                href={"#about"}
              >
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___7E0Fi
                  )}
                >
                  {"About me"}
                </div>
                <RightArrowIcon
                  className={classNames(projectcss.all, sty.svg___4NVqM)}
                  role={"img"}
                />
              </a>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"services"}
            data-plasmic-override={overrides.services}
            hasGap={true}
            className={classNames(projectcss.all, sty.services)}
            id={"Services"}
          >
            <div className={classNames(projectcss.all, sty.freeBox___1ZOLv)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text___04I0R
                )}
                id={"services"}
              >
                {"Services"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__mYfvj
                )}
              >
                {"Embracing constraints to push the boundaries."}
              </h2>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.columns__iJbr)}
            >
              <div className={classNames(projectcss.all, sty.column__vvlYx)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wH0PB)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: uxDesignpngBLz1FLdJ3JVx,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__bqI2C
                  )}
                >
                  {"UX/UI & Web \nDesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__lpu6O
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column___4JPcU)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__oxJag)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: brushpngR3QrLaI5Ix3S,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__wT5W
                  )}
                >
                  {"Branding & visual \ndesign"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__e6SXu
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
              <div className={classNames(projectcss.all, sty.column__r8ZVw)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__exqGz)}
                  displayHeight={"90px"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={"100%"}
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={"90px"}
                  loading={"lazy"}
                  src={{
                    src: programmingpngVFumlm5Giy4X,
                    fullWidth: 512,
                    fullHeight: 512,
                    aspectRatio: undefined
                  }}
                />

                <h3
                  className={classNames(
                    projectcss.all,
                    projectcss.h3,
                    projectcss.__wab_text,
                    sty.h3__aTQyn
                  )}
                >
                  {"Web \ndevelopment"}
                </h3>
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xhAm5
                  )}
                >
                  {
                    "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                  }
                </div>
              </div>
            </Stack__>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"work"}
            data-plasmic-override={overrides.work}
            hasGap={true}
            className={classNames(projectcss.all, sty.work)}
            id={"work"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__bgAFa)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gksXp
                )}
                id={"services"}
              >
                {"work"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__a9R4P
                )}
              >
                {"Privileged to work with on some amazing projects."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__aOZxG)}>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns__ebRpX)}
              >
                <div className={classNames(projectcss.all, sty.column__i0IH)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal___7USgT)}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__qM81O
                      )}
                      link={`/project-relaunch`}
                      title={"Project Relaunch"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column___77Akx)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__s2Jm)}
                    delay={250}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__f1TVi
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: abstractBackgroundJpg5P9VEsB5X25M,
                        fullWidth: 1920,
                        fullHeight: 1171,
                        aspectRatio: undefined
                      }}
                      link={`/website-redesign`}
                      title={"Website Redesign"}
                    />
                  </Reveal>
                </div>
              </Stack__>
              <Stack__
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.columns___7U0Nc)}
              >
                <div className={classNames(projectcss.all, sty.column__sgksQ)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__gqv7I)}
                    delay={500}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__bKiMr
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: abstractBackgroundWithSoftGradientColorAndDynamicShadowOnBackgroundBackgroundForWallpaperEps10FreeVectorjpgKbyRfUiqZq4S,
                        fullWidth: 1920,
                        fullHeight: 1080,
                        aspectRatio: undefined
                      }}
                      link={`/premium-sass-design`}
                      title={"Premium Saas Design"}
                    />
                  </Reveal>
                </div>
                <div className={classNames(projectcss.all, sty.column__cXtnf)}>
                  <Reveal
                    className={classNames("__wab_instance", sty.reveal__oqQlq)}
                    delay={750}
                    direction={"up"}
                    duration={500}
                    triggerOnce={true}
                  >
                    <ProjectCard
                      className={classNames(
                        "__wab_instance",
                        sty.projectCard__v5D5Y
                      )}
                      description={
                        "Aut cupiditate expedita dolor eveniet a autem rerum ut dicta. Exercitationem eum suscipit quo. Est fugiat ducimus aut saepe."
                      }
                      image={{
                        src: blueAndOrangeAbstractBackgroundFreeVectorjpg9ViVfovKbrrw,
                        fullWidth: 1920,
                        fullHeight: 1280,
                        aspectRatio: undefined
                      }}
                      link={`/web-visual-design`}
                      title={"Web Visual Graphic Design"}
                    />
                  </Reveal>
                </div>
              </Stack__>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"about"}
            data-plasmic-override={overrides.about}
            hasGap={true}
            className={classNames(projectcss.all, sty.about)}
            id={"about"}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uXa2O)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__gxldR
                )}
                id={"about"}
              >
                {"About Me"}
              </div>
            </div>
            <Stack__
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__u3DEc)}
            >
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__eeJy6
                )}
              >
                {"Bridging design and no-code."}
              </h2>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__wcKr
                )}
              >
                {
                  "Anna is an award winning, web designer specialising in no-code solutions. With over 8 years of professional experience I've helped countless startups launch & grow their business."
                }
              </div>
            </Stack__>
            <div className={classNames(projectcss.all, sty.freeBox__ofO9)}>
              <div className={classNames(projectcss.all, sty.freeBox__qoOUe)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wzxX)}
                >
                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__g4Azb)}
                    displayHeight={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "311px"
                        : "312px"
                    }
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    loading={"lazy"}
                    src={{
                      src: studentGa473640711280JpgRKsLA5I6R,
                      fullWidth: 1280,
                      fullHeight: 853,
                      aspectRatio: undefined
                    }}
                  />

                  <PlasmicImg__
                    alt={""}
                    className={classNames(sty.img__shVmn)}
                    displayHeight={"312px"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={
                      hasVariant(globalVariants, "screen", "mobileOnly")
                        ? "100%"
                        : "100%"
                    }
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"100%"}
                    loading={"lazy"}
                    src={{
                      src: lukePetersB6JiNerWMz0Unsplashjpg2ZrK6L4HpVe1,
                      fullWidth: 1920,
                      fullHeight: 1280,
                      aspectRatio: undefined
                    }}
                  />
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__tOPbq)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__wjPfT)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: benKoldeBs2Ba7T69MMUnsplashjpgUWij0Ll9570,
                    fullWidth: 1920,
                    fullHeight: 2449,
                    aspectRatio: undefined
                  }}
                />
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__ouNa5)}>
                <PlasmicImg__
                  alt={""}
                  className={classNames(sty.img__jMdSg)}
                  displayHeight={"100%"}
                  displayMaxHeight={"none"}
                  displayMaxWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  displayMinHeight={"0"}
                  displayMinWidth={"0"}
                  displayWidth={
                    hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "100%"
                      : "100%"
                  }
                  loading={"lazy"}
                  src={{
                    src: danielKorpaiAUmq852V7IUnsplashjpgLRgUox8TcW9,
                    fullWidth: 1920,
                    fullHeight: 2400,
                    aspectRatio: undefined
                  }}
                />
              </div>
            </div>
          </Stack__>
          <Stack__
            as={"section"}
            data-plasmic-name={"testimonials"}
            data-plasmic-override={overrides.testimonials}
            hasGap={true}
            className={classNames(projectcss.all, sty.testimonials)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uFgXe)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__xmKbJ
                )}
              >
                {"TESTIMONIALS"}
              </div>
              <h2
                className={classNames(
                  projectcss.all,
                  projectcss.h2,
                  projectcss.__wab_text,
                  sty.h2__oQrDz
                )}
              >
                {"Hear from the folks I've worked with."}
              </h2>
            </div>
            <div className={classNames(projectcss.all, sty.freeBox__xIldh)}>
              <div className={classNames(projectcss.all, sty.freeBox__mv9Gm)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__wum3N)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__sRost)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox___7JWw)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__cjk7W)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__zPv7)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__p1GB)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__wWEu)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__plPge)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3___0GYej
                      )}
                    >
                      {"Very experienced"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__hLdp
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__aLCaw)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__yJd5K
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___2UScf)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: alexSuprunZHvM3XioHoEUnsplashjpgLc7Tf8Rih8G,
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__pEq52
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__sycS
                          )}
                        >
                          {"Albert David"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__foc95
                          )}
                        >
                          {"Marketing Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__afy8L)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__dbnvm)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__gaCyd)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__f3FVv)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___0Piks)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__zgxaz)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__miP4)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__wXMmN
                      )}
                    >
                      {"Very fast & skillful"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__zSlLk
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__th623)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__k07Zr
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___24Hn4)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: christopherCampbellRDeoVtE7VOsUnsplashjpgBUqxgVggHjJ2,
                            fullWidth: 640,
                            fullHeight: 427,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__yrcaA
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__mQzQj
                          )}
                        >
                          {"Arolina"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___8SkmP
                          )}
                        >
                          {"Manager, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
              <div className={classNames(projectcss.all, sty.freeBox__s5Io)}>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xX1C)}
                >
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__gnl17)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__x0W)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___6Ye6)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___3IXx3)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__k2SId)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__s4Oun)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__sFhLe)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__meikY
                      )}
                    >
                      {"skilled communicator"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__phwl
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__us8LF)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__h6In7
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___90NuU)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: courtneyCookTsZo17R3M0SUnsplashjpg7KDmPjoff0Od,
                            fullWidth: 640,
                            fullHeight: 960,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__pqal2
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__bc2M6
                          )}
                        >
                          {"Firmona"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__kJpy2
                          )}
                        >
                          {"Founder, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                  <Stack__
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox__qvPiV)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.freeBox__a0FCs)}
                    >
                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___6KFlv)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___9I5Ex)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg___79Oxg)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__dWsKn)}
                        role={"img"}
                      />

                      <StarIcon
                        className={classNames(projectcss.all, sty.svg__puoQ4)}
                        role={"img"}
                      />
                    </div>
                    <h3
                      className={classNames(
                        projectcss.all,
                        projectcss.h3,
                        projectcss.__wab_text,
                        sty.h3__bz97V
                      )}
                    >
                      {"Great design skills"}
                    </h3>
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__cKj3Y
                      )}
                    >
                      {
                        '"Anna worked very closely with us, delivering such a well designed product. Great communication and quick turn around. Loved it!"'
                      }
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.columns__rP3PO)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__lQrfn
                        )}
                      >
                        <PlasmicImg__
                          alt={""}
                          className={classNames(sty.img___2Ii6W)}
                          displayHeight={"100px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100px"}
                          loading={"lazy"}
                          src={{
                            src: alexanderHippIEebWgY6LAUnsplashjpg4EMtYZpQeJWx,
                            fullWidth: 640,
                            fullHeight: 640,
                            aspectRatio: undefined
                          }}
                        />
                      </div>
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.column__ph0Ej
                        )}
                      >
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text__r9C4Q
                          )}
                        >
                          {"Motherson"}
                        </div>
                        <div
                          className={classNames(
                            projectcss.all,
                            projectcss.__wab_text,
                            sty.text___0WEq
                          )}
                        >
                          {"Design Lead, Company"}
                        </div>
                      </div>
                    </div>
                  </Stack__>
                </Stack__>
              </div>
            </div>
          </Stack__>
          <ContactSection
            data-plasmic-name={"contactSection"}
            data-plasmic-override={overrides.contactSection}
            className={classNames("__wab_instance", sty.contactSection)}
          />

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />

          {(() => {
            const child$Props = {
              className: classNames("__wab_instance", sty.dateTimePicker),
              onChange: generateStateOnChangePropForCodeComponents(
                $state,
                "value",
                ["dateTimePicker", "value"],
                AntdDatePicker_Helpers
              ),
              popupScopeClassName: sty["dateTimePicker__datePickerPopup"],
              value: generateStateValueProp($state, ["dateTimePicker", "value"])
            };
            initializeCodeComponentStates(
              $state,
              [
                {
                  name: "value",
                  plasmicStateName: "dateTimePicker.value"
                }
              ],

              [],
              AntdDatePicker_Helpers ?? {},
              child$Props
            );
            return (
              <AntdDatePicker
                data-plasmic-name={"dateTimePicker"}
                data-plasmic-override={overrides.dateTimePicker}
                {...child$Props}
              />
            );
          })()}
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navigationBar",
    "intro",
    "mainTextContainer",
    "h1",
    "link",
    "services",
    "work",
    "about",
    "testimonials",
    "contactSection",
    "footer",
    "dateTimePicker"
  ],

  navigationBar: ["navigationBar"],
  intro: ["intro", "mainTextContainer", "h1", "link"],
  mainTextContainer: ["mainTextContainer", "h1"],
  h1: ["h1"],
  link: ["link"],
  services: ["services"],
  work: ["work"],
  about: ["about"],
  testimonials: ["testimonials"],
  contactSection: ["contactSection"],
  footer: ["footer"],
  dateTimePicker: ["dateTimePicker"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicHomepage__ArgProps,
          internalVariantPropNames: PlasmicHomepage__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navigationBar: makeNodeComponent("navigationBar"),
    intro: makeNodeComponent("intro"),
    mainTextContainer: makeNodeComponent("mainTextContainer"),
    h1: makeNodeComponent("h1"),
    link: makeNodeComponent("link"),
    services: makeNodeComponent("services"),
    work: makeNodeComponent("work"),
    about: makeNodeComponent("about"),
    testimonials: makeNodeComponent("testimonials"),
    contactSection: makeNodeComponent("contactSection"),
    footer: makeNodeComponent("footer"),
    dateTimePicker: makeNodeComponent("dateTimePicker"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps,
    // Page metadata
    pageMetadata: {
      title: "Anna.Design",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse varius enim in eros elementum tristique. Duis cursus, mi quis viverra ornare, eros dolor interdum nulla, ut commodo diam libero vitae erat. Aenean faucibus nibh et justo cursus id rutrum lorem imperdiet. Nunc ut sem vitae risus tristique posuere.",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
